{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sparkxgb
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sparkxgb_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sparkxgb/sparkxgb_{{ version }}.tar.gz
  sha256: 6b2c185fccd1b66b851badc0035eb6c79b056ffb321ba59671169d7ba310d265

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-fs
    - r-magrittr
    - r-rlang
    - r-sparklyr
    - r-vctrs
  run:
    - r-base
    - r-fs
    - r-magrittr
    - r-rlang
    - r-sparklyr
    - r-vctrs

test:
  commands:
    - $R -e "library('sparkxgb')"           # [not win]
    - "\"%R%\" -e \"library('sparkxgb')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sparkxgb
  dev_url: https://github.com/rstudio/sparkxgb
  license: Apache-2.0
  summary: A 'sparklyr' <https://spark.posit.co/> extension that provides an  interface for 'XGBoost' <https://github.com/dmlc/xgboost> on 'Apache Spark'. 'XGBoost' is an  optimized distributed gradient boosting library.
  license_family: APACHE
  license_file: LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
