appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: bp/0IYQBHA8PxiPWHXGVGP2WBQk1PVx9m5F3zf96HKVtfmdo4JDCbnrsoxxcn5d+33MlU+vQ8VN51NiyalaEDBVzM+DvXG3AUpY8xRKitTaVB5ZSZ+t8hKcJDtjFgUAIyNvRY+6lO9y7h+lmeFRMAixfMNycGKU098YhRjkANjXiz07Ok9ahF/PksHaoPfJiWpRF2mnRP7SiVyBNZCByb2k9lYnympgvFONfuPVQBXBgnS6cXn6+27/lryBUn/V2aDF/mn6IjPH70HGWI0wxGClU2IRADJtsCNs7MO6LkoqfPS3WVtCVKLwvoMdo7l/8zYESrRwFBISbrgccOE3mB6tuVgZhQgePHRskiUOYkIId0o8zCXY2AjBNtiS6ZKz0rgNjqnt5VWjzopeDY8hCNXTnTqdJAgh7cVeOzxRBFTQXDuJl/oiJPbuQCCu127tNJP0wZxW1BAUey2/BITXqq4VXrn3GkS1RV/05l9Sd+Q+7IH/7/P9WO99JYhtUpbWNHZw153rPMocTtLa3FVTdUaN2r+KGjzOQFzCVigt1tnTaaJAeZNPnbW54jV5vL8JR9Q6CmxqH3ca21kqO/S4ATEtZvZdGpohny7kNzx25i+qeiQuLdMYUlvCzhe2bvN3d+0SaHHRpmSP5RvDnCqbup+KaV8OA9klNRHCwImuQMgo=}
bot:
  automerge: true
